openbox + Xorg settings update

diff --git a/config/openbox/autostart b/config/openbox/autostart
--- a/config/openbox/autostart
+++ b/config/openbox/autostart
@@ -1,31 +1,78 @@
-#!/bin/sh
+#!/usr/bin/env bash
+set -o errexit -o nounset -o pipefail
 
-# Do not beep
-xset b off
+# Get the basename of this program and the directory path to itself:
+readonly PROGNAME="${BASH_SOURCE[0]##*/}"
+readonly PROGPATH="$(realpath "${BASH_SOURCE[0]%/*}")"
 
-# Start X compositor daemonized (if existing in PATH)
-#compton -b
-xcompmgr -I.1 -O.08 -D10 -t-5 -l-5 -r12 -o.5 -CcFf &
+if [[ "${BASH_VERSINFO[0]}" -lt 4 ]]; then
+  echo >&2 "Bash version"
+  exit 1
+fi
 
-# Launch dzen script if available
-#[[ -x ~/.dzen.sh ]] && ~/.dzen.sh &
+# Notification stuff
+readonly NOTIF_TIMEOUT_MS=1000
+readonly NOTIF_SUMMARY="Openbox autostart script"
 
-# Nitrogen restores the background
-nitrogen --restore &
+main() {
+  # Do not beep
+  xset b off
 
-# Dunst for the desktop notification
-dunst -config ~/.config/dunst/dunstrc &
+  # Dunst for the desktop notification
+  dunst -config ~/.config/dunst/dunstrc &
+  notify 'dunst started.'
 
-# Tint2 and Conky for Openbox
-tint2 &
-#conky &
+  # Start X compositor daemonized (if existing in PATH)
+  xcompmgr -I '.1' -O '.08' -D '10' -t '-5' -l '-5' -r '12' -o '.5' -CcFf &
+  notify 'Compositor (xcompmgr) started.'
 
-# Volume icon
-volumeicon &
+  # Xrandr script generated by Arandr
+  if [ -x ~/.screenlayout/default.sh  ]; then
+    sleep 0.2   # wait 0.2 seconds otherwise second monitor may stay blank
+    ~/.screenlayout/default.sh
+    notify 'Screenlayout default script called.'
+  fi
 
-# Network Manager applet
-nm-applet &
+  # Nitrogen restores the wallpapers properly if spanned on multiple monitors
+  if nitrogen --restore; then
+    notify 'Wallpaper restored (nitrogen).'
+  else
+    notify 'Could not restore wallpaper (nitrogen).'
+  fi
 
-# XFCE Power manager daemon
-xfce4-power-manager &
+  # Tint2 (window status bar with tray icons)
+  tint2 &
+  notify 'Status bar (tint2) started.'
 
+  # Volume icon
+  volumeicon &
+  notify 'Volume icon applet (volumeicon) started.'
+
+  # Network Manager applet
+  nm-applet &
+  notify 'NetworkManager applet (nm-applet) started.'
+}
+
+notify() {
+  local urgency=normal
+  local opt
+  while getopts ":u:" opt; do
+    case "$opt" in
+      u)
+        echo >&2 "-a was triggered!" >&2
+        ;;
+      :)
+        echo >&2 "Invalid option: -$OPTARG"
+        return 1
+        ;;
+    esac
+  done
+  command -v notify-send >/dev/null 2>&1 || return 0  # fail silently for this
+  notify-send \
+    -t "$NOTIF_TIMEOUT_MS" -u "$urgency" -a "${BASH_SOURCE[0]##*/}" \
+    "$NOTIF_SUMMARY" "$*"
+}
+
+main "$@"
+
+# vim: set ts=2 sts=2 sw=2 et:
